import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import Hero2 from '@/components/Hero2'
import Navbar from '@/components/Navbar'
import TopBar from '@/components/TopBar'
import Hero3 from '@/components/Hero3'
import Hero4 from '@/components/Hero4'
import Hero5 from '@/components/Hero5'
import Hero6 from '@/components/Hero6'
import Hero7 from '@/components/Hero7'
import Footer from '@/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Electric Cars, Solar and Clean Energy | Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <TopBar /> */}
        <Navbar />
        <Hero />
        <Hero2 />
        <Hero3 />
        <Hero4 />
        <Hero5 />
        <Hero6 />
        <Hero7 />
        <Footer />
      </main>
    </>
  )
}
